### ISSUE TITLE
no output and endless wait

### ISSUE THREAD

**Issue by celevra** [crowdsecurity/cs-express-bouncer#1]
hi,

i'm trying to include it like this:

```
app.use(require('./libs/crowdsec.js'));
```
crowdsec.js
```
"use strict"
//crowdsec
const expressCrowdsecBouncer = require("@crowdsec/express-bouncer");
// Configure CrowdSec Middleware.
async function crowdsec() {
    const crowdsecMiddleware = await expressCrowdsecBouncer({
        url: "http://xxx:8181",
        apiKey: "xxx",
    });
}

module.exports = crowdsec;
```

but i receive no log output, and all my routes are loading endless

regards

**Comment by LaurenceJJones** [comment]
How are you using the exported module within express? because the exported module doesnt return a value, so I dont know what you expect to see on the other side

Edit: sorry I saw it at the top:

You need to return a value to the crowdsec function

```js
"use strict"
//crowdsec
const expressCrowdsecBouncer = require("@crowdsec/express-bouncer");
// Configure CrowdSec Middleware.
async function crowdsec() {
    const crowdsecMiddleware = await expressCrowdsecBouncer({
        url: "http://xxx:8181",
        apiKey: "xxx",
    });
   return crowdsecMiddleware;
}

module.exports = crowdsec;
```

But then your import should invoke the function, however, its a async function so you have to wait the value

```js
app.use(await require('./libs/crowdsec.js')());
```

Just tested the implementation above all works fine for me.

**Comment by LaurenceJJones** [comment]
Hey 👋🏻 I will class this as completed but feel free to reopen if my reply was not sufficient
